version: "3"

tasks:
  init_backend:
    dir: ./backend
    desc: Init poetry
    cmds:
      - poetry shell
    task: run_backend

  install_app_dependencies:
    dir: ./app
    desc: Install dependencies
    cmds:
      - yarn

  run_app:
    dir: ./app
    desc: Start app
    cmds:
      - yarn serve
