version: "3"

tasks:
  init_env:
    desc: Init environment
    cmds:
      - poetry shell

  install_dependencies:
    desc: Intall dependencies
    cmds:
      - poetry install

  run:
    desc: Start Server
    cmds:
      - poetry run python manage.py runserver

  tests:
    desc: Run backend tests
    cmds:
      - poetry run python manage.py test
