# Generated by Django 3.2.4 on 2021-06-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=400)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('description', models.TextField(default='', max_length=5000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='git_api.author')),
            ],
            options={
                'db_table': 'pull_requests',
            },
        ),
    ]
