# Generated by Django 3.2.4 on 2021-06-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='from_branch',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='to_breanch',
            field=models.TextField(default='', max_length=200),
        ),
    ]
