# Generated by Django 3.2.4 on 2021-06-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_api', '0002_auto_20210616_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='to_breanch',
            new_name='to_branch',
        ),
    ]
