# Generated by Django 3.2.4 on 2021-06-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_api', '0003_rename_to_breanch_pullrequest_to_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('from_branch', 'to_branch')},
        ),
    ]
